apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "physiotherapy-app.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: FRONTEND_URL
              value: {{ .Values.backend.env.FRONTEND_URL | quote }}
            - name: PORT
              value: {{ .Values.backend.env.PORT | quote }}
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "physiotherapy-app.fullname" . }}-secrets
                  key: MONGO_URI
